excluded:
  - Packages/JellyseerrAPI
  - vendor

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 800
  error: 1000

type_body_length:
  warning: 550
  error: 700

function_body_length:
  warning: 60
  error: 80

nesting:
  type_level: 2
  function_level: 2

identifier_name:
  excluded:
    - id
